# our base image
FROM ubuntu:18.04

# Install python and pip
RUN apt update
RUN apt install -y python3 python3-pip

# install Python modules needed by the Python app
COPY requirements-step1.txt /usr/src/app/
COPY scripts/step1.sh /

RUN cat /usr/src/app/requirements-step1.txt
RUN pip3 install --no-cache-dir -r /usr/src/app/requirements-step1.txt
